# Brief: Contains all constants used on all programs
# Author: Alexandre Kaihara and Pedro

# other
PROCESS_DO_NOT_EXISTS = -100                          # WHEN ANY OPERATION ON SYSTEM COULD NOT BE COMPLETED BECAUSE GIVEN PROCESS ID DOES NOT EXIST
PROCESS_FINISHED = 11
PROCESS_CREATION_FINISHED = 12

# arquivo.py
CREATE_FILE_SUCESS = 100                            # WHEN A FILE COULD BE CREATED AND THERE WAS ENOUGTH MEMORY
CREATE_FILE_NOT_ENOUGTH_MEM = 101                   # WHEN A FILE COULD NOT BE CREATED BECAUSE OF NOT ENOUGTH MEMORY
DELETE_FILE_SUCESS = 110                            # WHEN A FILE COULD BE DELETED
DELETE_FILE_NOT_PERMITTED = 111                     # WHEN A PROCESS DOESN'T HAVE PERMISSION TO DELETE THE FILE
FILE_NOT_FOUND = 120                                # WHEN GIVEN FILENAME COULD NOT BE FOUND ON MEMORY
CREATE_FILE_REQUEST = 0
DELETE_FILE_REQUEST = 1
NO_FILE_REQUEST = 132

# memoria.py
NOT_ENOUGH_RAM_MEMORY = 200                         # WHEN THERE IS NO FREE SPACE ON RAM FOR A PROCESS
MEMORY_ALLOCATION_SUCESS = 201

# fila.py
NO_NEXT_PROCESS = -1                               # WHEN THE SCHEDULER HAS NO PROCESS TO BE EXECUTED

# processos.py
NO_RESOURCE_REQUEST = 400                           # WHEN THE RUNNING PROCESS DIDN'T REQUEST A RESOURCE
SCANNER_RESOURCE_REQUESTED = 401                    # WHEN THE RUNNING PROCESS REQUEST A SCANNER
PRINTER_RESOURCE_REQUESTED = 402                    # WHEN THE RUNNING PROCESS REQUEST A PRINTER
MODEM_RESOURCE_REQUESTED = 403                      # WHEN THE RUNNING PROCESS REQUEST A MODEM
SATA_RESOURCE_REQUESTED = 404                       # WHEN THE RUNNING PROCESS REQUEST A SATA
ARCHIVE_ACTION = 410
INSTRUCTION_ACTION = 411
RESOURCE_ACTION = 412


def diff_time(time1, time2):
    delta = time1 - time2
    return delta.seconds + delta.microseconds/1000000
