# Brief: Contains all constants used on all programs
# Author: Alexandre Kaihara and Pedro

# other
PROCESS_DO_NOT_EXISTS = 00                          # WHEN ANY OPERATION ON SYSTEM COULD NOT BE COMPLETED BECAUSE GIVEN PROCESS ID DOES NOT EXIST

# arquivo.py
CREATE_FILE_SUCESS = 100                            # WHEN A FILE COULD BE CREATED AND THERE WAS ENOUGTH MEMORY
CREATE_FILE_NOT_ENOUGTH_MEM = 101                   # WHEN A FILE COULD NOT BE CREATED BECAUSE OF NOT ENOUGTH MEMORY
DELETE_FILE_SUCESS = 110                            # WHEN A FILE COULD BE DELETED
DELETE_FILE_NOT_PERMITTED = 111                     # WHEN A PROCESS DOESN'T HAVE PERMISSION TO DELETE THE FILE
FILE_NOT_FOUND = 120                                # WHEN GIVEN FILENAME COULD NOT BE FOUND ON MEMORY


